# Permalinks

# Setup
title:              'Israel Messias Júnior'
tagline:            'Developer'
url:                https://curriculo.jrmessias.com.br
baseurl:            ''
twitter:            jrmessias

googleanalytics: "G-SMX0451JVM"

exclude:
  - package.json
  - postcss.config.js
  - readme.md
  - run.bat
  - tailwind.config.js
  - feed.xml