# Permalinks

# Setup
title:              'Israel Messias Júnior'
tagline:            'Developer'
url:                https://jrmessias.com.br/resume
baseurl:            ''
twitter:            jrmessias

exclude:
  - package.json
  - postcss.config.js
  - readme.md
  - run.bat
  - tailwind.config.js
  - feed.xml