title: Israel Aparecido Messias Júnior
description:  Currículo
url: https://curriculo.jrmessias.com.br
baseurl: ''
theme_skin: green

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
